name: HireFlow API CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.14
          cache: true

      - name: Install root dependencies
        run: bun install --frozen-lockfile

      - name: Run Lint
        run: bun lint

      - name: Run Type Check
        run: bun type-check

      - name: Run Format Check
        run: bun run check

      - name: Build Project
        run: bun run build
